'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const P = require('../src/g2/product');
function plan(approval_required = false) { return P.plan.createPlan({ plan_id: 'p1', goal: 'ship product', approval_required, steps: [{ id: 's1', description: 'implement' }, { id: 's2', description: 'verify' }] }); }
test('ordinary plan preview is informational instead of a wait gate', () => { const preview = P.humanInterface.planPreview({ plan: plan(false) }); assert.equal(preview.informational, true); assert.equal(preview.approval_required, false); assert.equal(preview.steps.length, 2); });
test('approval-required plan preview exposes the decision gate', () => { const preview = P.humanInterface.planPreview({ plan: plan(true) }); assert.equal(preview.informational, false); assert.equal(preview.approval_required, true); });
test('progress summary exposes completed active remaining and next', () => { const progress = P.humanInterface.progressSummary({ completed: ['intake'], active: ['implementation'], remaining: ['verification'], next: 'finish implementation' }); assert.equal(progress.status, 'CONTINUE'); assert.match(progress.summary, /Completed: intake/); assert.match(progress.summary, /Next: finish implementation/); });
test('actionable blocker says exactly what user must provide and resume point', () => { const report = P.humanInterface.blockerReport({ action: 'BLOCKED_USER_ACTION', reason: 'source file missing', completed: ['claim analysis'], required_user_input: 'provide the source file', resume_from: 'compare source with claims' }); assert.equal(report.user_action_required, true); assert.match(report.message, /User action: provide the source file/); assert.match(report.message, /Resume: compare source with claims/); });
test('external blocker does not shift platform problem onto user', () => { const report = P.humanInterface.blockerReport({ action: 'BLOCKED_EXTERNAL', reason: 'provider unavailable', resume_from: 'retry provider read' }); assert.equal(report.user_action_required, false); assert.match(report.message, /User action: none/); });
test('actionable blocker without concrete requested input is rejected', () => { assert.throws(() => P.humanInterface.blockerReport({ action: 'BLOCKED_DECISION', reason: 'strategy choice required', resume_from: 'execute chosen strategy' }), /requires required_user_input/); });
